version: '3.7'

services:
  mysql-dev:
    image: mysql:8
    container_name: kupec-mysql-dev
    ports:
      - "3313:3306"
    environment:
      - MYSQL_DATABASE=kupec
      - MYSQL_ROOT_PASSWORD=kupec-password
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
    networks:
      - kupec-dev-net

networks:
  kupec-dev-net:
    driver: bridge
